@startuml

Class Personje
class Imagen
Class sprite
Class Teclado
Class Texto 
Class Ventana
Class Audio
Class Config
Class GpuPreference
Class Graphics
Class Main 
Class Network
Class OpenGL
Class System
Class Window

Personje --|> Sprite
Personje -- Teclado
Sprite --|> Imagen
Ventana --|> Graphics
Ventana -- Audio
Config --|> GpuPreference
Config --|> Graphics
Main -- Network
Main -- OpenGL
Main -- Config
Main -- System
Main -- Window

@enduml